import '..';
import { render, unmountComponentAtNode } from 'react-dom'
import { flush, presets, styleSheet } from 'glamor';
import React from 'react';
import expect from 'expect'

describe('glamor-reset', () => {

  it('inserts normalize styles', () => {
    expect(styleSheet.rules().map((x, ctx) => x.cssText).join('\n')).toEqual(`html { font-family: sans-serif; line-height: 1.15; }\nbody { margin: 0px; }\narticle, aside, footer, header, nav, section { display: block; }\nh1 { font-size: 2em; margin: 0.67em 0px; }\nfigcaption, figure, main { display: block; }\nfigure { margin: 1em 40px; }\nhr { box-sizing: content-box; height: 0px; overflow: visible; }\npre { font-family: monospace, monospace; font-size: 1em; }\na { background-color: transparent; }\na:active, a:hover { outline-width: 0px; }\nabbr[title] { border-bottom-style: none; text-decoration: underline; }\nb, strong { font-weight: inherit; }\nb, strong { font-weight: bolder; }\ncode, kbd, samp { font-family: monospace, monospace; font-size: 1em; }\ndfn { font-style: italic; }\nmark { background-color: rgb(255, 255, 0); color: rgb(0, 0, 0); }\nsmall { font-size: 80%; }\nsub, sup { font-size: 75%; line-height: 0; position: relative; vertical-align: baseline; }\nsub { bottom: -0.25em; }\nsup { top: -0.5em; }\naudio, video { display: inline-block; }\naudio:not([controls]) { display: none; height: 0px; }\nimg { border-style: none; }\nsvg:not(:root) { overflow: hidden; }\nbutton, input, optgroup, select, textarea { font-family: sans-serif; font-size: 100%; line-height: 1.15; margin: 0px; }\nbutton, input { overflow: visible; }\nbutton, select { text-transform: none; }\nbutton, html [type="button"], [type="reset"], [type="submit"] { -webkit-appearance: button; }\nfieldset { border: 1px solid rgb(192, 192, 192); margin: 0px 2px; padding: 0.35em 0.625em 0.75em; }\nlegend { box-sizing: border-box; color: inherit; display: table; max-width: 100%; padding: 0px; white-space: normal; }\nprogress { display: inline-block; vertical-align: baseline; }\ntextarea { overflow: auto; }\n[type="checkbox"], [type="radio"] { box-sizing: border-box; padding: 0px; }\n[type="number"]::-webkit-inner-spin-button, [type="number"]::-webkit-outer-spin-button { height: auto; }\n[type="search"] { -webkit-appearance: textfield; outline-offset: -2px; }\n[type="search"]::-webkit-search-cancel-button, [type="search"]::-webkit-search-decoration { -webkit-appearance: none; }\n*::-webkit-file-upload-button { -webkit-appearance: button; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; line-height: inherit; }\ndetails, menu { display: block; }\nsummary { display: list-item; }\ncanvas { display: inline-block; }\ntemplate { display: none; }\n[hidden] { display: none; }`)
    })
})
