import { styleSheet } from './index.js'

/**** serverside stuff ****/

// the api's copied from aphrodite, with 1 key difference 
// we include *all* the css generated by the app 
// to optimize to only include generated styles on the pages 
// use renderStaticOptimized
export function renderStatic(fn, optimized = false) {
  let html = fn()
  if(html === undefined) {
    throw new Error('did you forget to return from renderToString?')
  }
  let rules = styleSheet.rules(), css = rules.map(r => r.cssText).join('\n')
  if(optimized) {
    // parse out ids from html
    // reconstruct css/rules/cache to pass

    let o = { html, cache: {}, css: '' }
    let regex = /data\-css\-([a-zA-Z0-9]+)=/gm
    let match, ids = []
    while((match = regex.exec(html)) !== null) {
      ids.push(match[1])
    }
    ids.forEach(id => {
      o.cache[id] = styleSheet.cache[id]
      
      // todo - add fonts / animations
      o.css+= rules
        .map(x => x.cssText)
        .filter(r => new RegExp(`\\\[data\-css\-${id}\\\]`).test(r)).join('\n') + '\n'
    })
    return o

  }
  return { html, cache: styleSheet.cache, css }
}

export function renderStaticOptimized(fn) {
  return renderStatic(fn, true)
}

export function rehydrate(c) {
  // load up cache
  styleSheet.cache = { ...styleSheet.cache, ...c }
  // assume css loaded separately
}
